# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/Users/Julian/Desktop/MathApp.ui'
#
# Created by: PyQt5 UI code generator 5.12.3
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(761, 472)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(10, 0, 761, 431))
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.label_4 = QtWidgets.QLabel(self.tab)
        self.label_4.setGeometry(QtCore.QRect(25, 110, 81, 31))
        self.label_4.setObjectName("label_4")
        self.label = QtWidgets.QLabel(self.tab)
        self.label.setGeometry(QtCore.QRect(25, 20, 71, 21))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.tab)
        self.label_2.setGeometry(QtCore.QRect(25, 60, 81, 31))
        self.label_2.setObjectName("label_2")
        self.convert_button = QtWidgets.QPushButton(self.tab)
        self.convert_button.setGeometry(QtCore.QRect(20, 170, 121, 61))
        self.convert_button.setObjectName("convert_button")
        self.bc_result = QtWidgets.QTextBrowser(self.tab)
        self.bc_result.setGeometry(QtCore.QRect(25, 250, 391, 131))
        self.bc_result.setObjectName("bc_result")
        self.bc_number = QtWidgets.QLineEdit(self.tab)
        self.bc_number.setGeometry(QtCore.QRect(113, 20, 224, 21))
        self.bc_number.setText("")
        self.bc_number.setObjectName("bc_number")
        self.bc_from_base = QtWidgets.QComboBox(self.tab)
        self.bc_from_base.setGeometry(QtCore.QRect(110, 60, 231, 31))
        self.bc_from_base.setEditable(False)
        self.bc_from_base.setObjectName("bc_from_base")
        self.bc_from_base.addItem("")
        self.bc_from_base.addItem("")
        self.bc_from_base.addItem("")
        self.bc_from_base.addItem("")
        self.bc_from_base.addItem("")
        self.bc_from_base.addItem("")
        self.bc_from_base.addItem("")
        self.bc_from_base.addItem("")
        self.bc_from_base.addItem("")
        self.bc_from_base.addItem("")
        self.bc_from_base.addItem("")
        self.bc_from_base.addItem("")
        self.bc_from_base.addItem("")
        self.bc_from_base.addItem("")
        self.bc_from_base.addItem("")
        self.bc_from_base.addItem("")
        self.bc_from_base.addItem("")
        self.bc_from_base.addItem("")
        self.bc_from_base.addItem("")
        self.bc_from_base.addItem("")
        self.bc_from_base.addItem("")
        self.bc_from_base.addItem("")
        self.bc_from_base.addItem("")
        self.bc_from_base.addItem("")
        self.bc_from_base.addItem("")
        self.bc_from_base.addItem("")
        self.bc_from_base.addItem("")
        self.bc_from_base.addItem("")
        self.bc_from_base.addItem("")
        self.bc_from_base.addItem("")
        self.bc_from_base.addItem("")
        self.bc_from_base.addItem("")
        self.bc_from_base.addItem("")
        self.bc_from_base.addItem("")
        self.bc_from_base.addItem("")
        self.bc_to_base = QtWidgets.QComboBox(self.tab)
        self.bc_to_base.setGeometry(QtCore.QRect(110, 110, 231, 31))
        self.bc_to_base.setEditable(False)
        self.bc_to_base.setObjectName("bc_to_base")
        self.bc_to_base.addItem("")
        self.bc_to_base.addItem("")
        self.bc_to_base.addItem("")
        self.bc_to_base.addItem("")
        self.bc_to_base.addItem("")
        self.bc_to_base.addItem("")
        self.bc_to_base.addItem("")
        self.bc_to_base.addItem("")
        self.bc_to_base.addItem("")
        self.bc_to_base.addItem("")
        self.bc_to_base.addItem("")
        self.bc_to_base.addItem("")
        self.bc_to_base.addItem("")
        self.bc_to_base.addItem("")
        self.bc_to_base.addItem("")
        self.bc_to_base.addItem("")
        self.bc_to_base.addItem("")
        self.bc_to_base.addItem("")
        self.bc_to_base.addItem("")
        self.bc_to_base.addItem("")
        self.bc_to_base.addItem("")
        self.bc_to_base.addItem("")
        self.bc_to_base.addItem("")
        self.bc_to_base.addItem("")
        self.bc_to_base.addItem("")
        self.bc_to_base.addItem("")
        self.bc_to_base.addItem("")
        self.bc_to_base.addItem("")
        self.bc_to_base.addItem("")
        self.bc_to_base.addItem("")
        self.bc_to_base.addItem("")
        self.bc_to_base.addItem("")
        self.bc_to_base.addItem("")
        self.bc_to_base.addItem("")
        self.bc_to_base.addItem("")
        self.swap_button = QtWidgets.QPushButton(self.tab)
        self.swap_button.setGeometry(QtCore.QRect(300, 170, 121, 61))
        self.swap_button.setObjectName("swap_button")
        self.reset_button = QtWidgets.QPushButton(self.tab)
        self.reset_button.setGeometry(QtCore.QRect(160, 170, 121, 61))
        self.reset_button.setObjectName("reset_button")
        self.bc_clear = QtWidgets.QPushButton(self.tab)
        self.bc_clear.setGeometry(QtCore.QRect(430, 245, 113, 32))
        self.bc_clear.setObjectName("bc_clear")
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.bo_add = QtWidgets.QPushButton(self.tab_2)
        self.bo_add.setGeometry(QtCore.QRect(360, 230, 51, 51))
        self.bo_add.setObjectName("bo_add")
        self.bo_minus = QtWidgets.QPushButton(self.tab_2)
        self.bo_minus.setGeometry(QtCore.QRect(430, 230, 51, 51))
        self.bo_minus.setObjectName("bo_minus")
        self.bo_mult = QtWidgets.QPushButton(self.tab_2)
        self.bo_mult.setGeometry(QtCore.QRect(500, 230, 51, 51))
        self.bo_mult.setObjectName("bo_mult")
        self.bo_divide = QtWidgets.QPushButton(self.tab_2)
        self.bo_divide.setGeometry(QtCore.QRect(570, 230, 51, 51))
        self.bo_divide.setObjectName("bo_divide")
        self.bo_result = QtWidgets.QTextBrowser(self.tab_2)
        self.bo_result.setGeometry(QtCore.QRect(25, 140, 291, 241))
        self.bo_result.setObjectName("bo_result")
        self.bo_number = QtWidgets.QLineEdit(self.tab_2)
        self.bo_number.setGeometry(QtCore.QRect(95, 40, 221, 21))
        self.bo_number.setText("")
        self.bo_number.setObjectName("bo_number")
        self.label_3 = QtWidgets.QLabel(self.tab_2)
        self.label_3.setGeometry(QtCore.QRect(25, 40, 71, 21))
        self.label_3.setObjectName("label_3")
        self.label_6 = QtWidgets.QLabel(self.tab_2)
        self.label_6.setGeometry(QtCore.QRect(370, 33, 81, 31))
        self.label_6.setObjectName("label_6")
        self.bo_from_base = QtWidgets.QComboBox(self.tab_2)
        self.bo_from_base.setGeometry(QtCore.QRect(440, 33, 161, 31))
        self.bo_from_base.setEditable(False)
        self.bo_from_base.setObjectName("bo_from_base")
        self.bo_from_base.addItem("")
        self.bo_from_base.addItem("")
        self.bo_from_base.addItem("")
        self.bo_from_base.addItem("")
        self.bo_from_base.addItem("")
        self.bo_from_base.addItem("")
        self.bo_from_base.addItem("")
        self.bo_from_base.addItem("")
        self.bo_from_base.addItem("")
        self.bo_from_base.addItem("")
        self.bo_from_base.addItem("")
        self.bo_from_base.addItem("")
        self.bo_from_base.addItem("")
        self.bo_from_base.addItem("")
        self.bo_from_base.addItem("")
        self.bo_from_base.addItem("")
        self.bo_from_base.addItem("")
        self.bo_from_base.addItem("")
        self.bo_from_base.addItem("")
        self.bo_from_base.addItem("")
        self.bo_from_base.addItem("")
        self.bo_from_base.addItem("")
        self.bo_from_base.addItem("")
        self.bo_from_base.addItem("")
        self.bo_from_base.addItem("")
        self.bo_from_base.addItem("")
        self.bo_from_base.addItem("")
        self.bo_from_base.addItem("")
        self.bo_from_base.addItem("")
        self.bo_from_base.addItem("")
        self.bo_from_base.addItem("")
        self.bo_from_base.addItem("")
        self.bo_from_base.addItem("")
        self.bo_from_base.addItem("")
        self.bo_from_base.addItem("")
        self.label_8 = QtWidgets.QLabel(self.tab_2)
        self.label_8.setGeometry(QtCore.QRect(370, 140, 81, 31))
        self.label_8.setObjectName("label_8")
        self.bo_to_base = QtWidgets.QComboBox(self.tab_2)
        self.bo_to_base.setGeometry(QtCore.QRect(440, 140, 161, 31))
        self.bo_to_base.setEditable(False)
        self.bo_to_base.setObjectName("bo_to_base")
        self.bo_to_base.addItem("")
        self.bo_to_base.addItem("")
        self.bo_to_base.addItem("")
        self.bo_to_base.addItem("")
        self.bo_to_base.addItem("")
        self.bo_to_base.addItem("")
        self.bo_to_base.addItem("")
        self.bo_to_base.addItem("")
        self.bo_to_base.addItem("")
        self.bo_to_base.addItem("")
        self.bo_to_base.addItem("")
        self.bo_to_base.addItem("")
        self.bo_to_base.addItem("")
        self.bo_to_base.addItem("")
        self.bo_to_base.addItem("")
        self.bo_to_base.addItem("")
        self.bo_to_base.addItem("")
        self.bo_to_base.addItem("")
        self.bo_to_base.addItem("")
        self.bo_to_base.addItem("")
        self.bo_to_base.addItem("")
        self.bo_to_base.addItem("")
        self.bo_to_base.addItem("")
        self.bo_to_base.addItem("")
        self.bo_to_base.addItem("")
        self.bo_to_base.addItem("")
        self.bo_to_base.addItem("")
        self.bo_to_base.addItem("")
        self.bo_to_base.addItem("")
        self.bo_to_base.addItem("")
        self.bo_to_base.addItem("")
        self.bo_to_base.addItem("")
        self.bo_to_base.addItem("")
        self.bo_to_base.addItem("")
        self.bo_to_base.addItem("")
        self.label_9 = QtWidgets.QLabel(self.tab_2)
        self.label_9.setGeometry(QtCore.QRect(25, 110, 60, 16))
        self.label_9.setObjectName("label_9")
        self.bo_clear = QtWidgets.QPushButton(self.tab_2)
        self.bo_clear.setGeometry(QtCore.QRect(220, 105, 101, 31))
        self.bo_clear.setObjectName("bo_clear")
        self.bo_equal = QtWidgets.QPushButton(self.tab_2)
        self.bo_equal.setGeometry(QtCore.QRect(360, 300, 91, 51))
        self.bo_equal.setObjectName("bo_equal")
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.label_5 = QtWidgets.QLabel(self.tab_3)
        self.label_5.setGeometry(QtCore.QRect(25, 40, 71, 21))
        self.label_5.setObjectName("label_5")
        self.tt_statement = QtWidgets.QLineEdit(self.tab_3)
        self.tt_statement.setGeometry(QtCore.QRect(110, 40, 611, 21))
        self.tt_statement.setText("")
        self.tt_statement.setObjectName("tt_statement")
        self.tt_result = QtWidgets.QTextBrowser(self.tab_3)
        self.tt_result.setGeometry(QtCore.QRect(25, 111, 351, 271))
        self.tt_result.setObjectName("tt_result")
        self.tt_clear = QtWidgets.QPushButton(self.tab_3)
        self.tt_clear.setGeometry(QtCore.QRect(390, 105, 113, 32))
        self.tt_clear.setObjectName("tt_clear")
        self.label_10 = QtWidgets.QLabel(self.tab_3)
        self.label_10.setGeometry(QtCore.QRect(25, 80, 60, 16))
        self.label_10.setObjectName("label_10")
        self.tabWidget.addTab(self.tab_3, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.label_7 = QtWidgets.QLabel(self.tab_4)
        self.label_7.setGeometry(QtCore.QRect(40, 40, 101, 16))
        self.label_7.setObjectName("label_7")
        self.label_11 = QtWidgets.QLabel(self.tab_4)
        self.label_11.setGeometry(QtCore.QRect(40, 80, 71, 16))
        self.label_11.setObjectName("label_11")
        self.label_12 = QtWidgets.QLabel(self.tab_4)
        self.label_12.setGeometry(QtCore.QRect(40, 120, 81, 16))
        self.label_12.setObjectName("label_12")
        self.label_13 = QtWidgets.QLabel(self.tab_4)
        self.label_13.setGeometry(QtCore.QRect(140, 80, 16, 16))
        self.label_13.setObjectName("label_13")
        self.label_14 = QtWidgets.QLabel(self.tab_4)
        self.label_14.setGeometry(QtCore.QRect(250, 80, 16, 16))
        self.label_14.setObjectName("label_14")
        self.label_15 = QtWidgets.QLabel(self.tab_4)
        self.label_15.setGeometry(QtCore.QRect(360, 80, 16, 16))
        self.label_15.setObjectName("label_15")
        self.label_16 = QtWidgets.QLabel(self.tab_4)
        self.label_16.setGeometry(QtCore.QRect(140, 120, 16, 16))
        self.label_16.setObjectName("label_16")
        self.label_17 = QtWidgets.QLabel(self.tab_4)
        self.label_17.setGeometry(QtCore.QRect(250, 120, 16, 16))
        self.label_17.setObjectName("label_17")
        self.label_18 = QtWidgets.QLabel(self.tab_4)
        self.label_18.setGeometry(QtCore.QRect(360, 120, 16, 16))
        self.label_18.setObjectName("label_18")
        self.x1 = QtWidgets.QLineEdit(self.tab_4)
        self.x1.setGeometry(QtCore.QRect(160, 80, 71, 21))
        self.x1.setObjectName("x1")
        self.x2 = QtWidgets.QLineEdit(self.tab_4)
        self.x2.setGeometry(QtCore.QRect(160, 120, 71, 21))
        self.x2.setObjectName("x2")
        self.y1 = QtWidgets.QLineEdit(self.tab_4)
        self.y1.setGeometry(QtCore.QRect(270, 80, 71, 21))
        self.y1.setObjectName("y1")
        self.y2 = QtWidgets.QLineEdit(self.tab_4)
        self.y2.setGeometry(QtCore.QRect(270, 120, 71, 21))
        self.y2.setObjectName("y2")
        self.z1 = QtWidgets.QLineEdit(self.tab_4)
        self.z1.setGeometry(QtCore.QRect(380, 80, 71, 21))
        self.z1.setObjectName("z1")
        self.z2 = QtWidgets.QLineEdit(self.tab_4)
        self.z2.setGeometry(QtCore.QRect(380, 120, 71, 21))
        self.z2.setObjectName("z2")
        self.label_19 = QtWidgets.QLabel(self.tab_4)
        self.label_19.setGeometry(QtCore.QRect(140, 310, 16, 16))
        self.label_19.setObjectName("label_19")
        self.label_20 = QtWidgets.QLabel(self.tab_4)
        self.label_20.setGeometry(QtCore.QRect(40, 270, 71, 16))
        self.label_20.setObjectName("label_20")
        self.n2 = QtWidgets.QLineEdit(self.tab_4)
        self.n2.setGeometry(QtCore.QRect(160, 310, 71, 21))
        self.n2.setObjectName("n2")
        self.n1 = QtWidgets.QLineEdit(self.tab_4)
        self.n1.setGeometry(QtCore.QRect(160, 270, 71, 21))
        self.n1.setObjectName("n1")
        self.label_21 = QtWidgets.QLabel(self.tab_4)
        self.label_21.setGeometry(QtCore.QRect(40, 310, 81, 16))
        self.label_21.setObjectName("label_21")
        self.label_22 = QtWidgets.QLabel(self.tab_4)
        self.label_22.setGeometry(QtCore.QRect(140, 270, 16, 16))
        self.label_22.setObjectName("label_22")
        self.label_23 = QtWidgets.QLabel(self.tab_4)
        self.label_23.setGeometry(QtCore.QRect(40, 240, 101, 16))
        self.label_23.setObjectName("label_23")
        self.add1 = QtWidgets.QPushButton(self.tab_4)
        self.add1.setGeometry(QtCore.QRect(270, 260, 113, 32))
        self.add1.setObjectName("add1")
        self.add2 = QtWidgets.QPushButton(self.tab_4)
        self.add2.setGeometry(QtCore.QRect(270, 300, 113, 32))
        self.add2.setObjectName("add2")
        self.label_24 = QtWidgets.QLabel(self.tab_4)
        self.label_24.setGeometry(QtCore.QRect(80, 180, 60, 16))
        self.label_24.setObjectName("label_24")
        self.output1 = QtWidgets.QTextBrowser(self.tab_4)
        self.output1.setGeometry(QtCore.QRect(150, 180, 191, 21))
        self.output1.setObjectName("output1")
        self.output2 = QtWidgets.QTextBrowser(self.tab_4)
        self.output2.setGeometry(QtCore.QRect(150, 350, 191, 21))
        self.output2.setObjectName("output2")
        self.label_25 = QtWidgets.QLabel(self.tab_4)
        self.label_25.setGeometry(QtCore.QRect(80, 350, 60, 16))
        self.label_25.setObjectName("label_25")
        self.calculate1 = QtWidgets.QPushButton(self.tab_4)
        self.calculate1.setGeometry(QtCore.QRect(360, 170, 113, 32))
        self.calculate1.setObjectName("calculate1")
        self.calculate2 = QtWidgets.QPushButton(self.tab_4)
        self.calculate2.setGeometry(QtCore.QRect(360, 340, 113, 32))
        self.calculate2.setObjectName("calculate2")
        self.tabWidget.addTab(self.tab_4, "")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 761, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(3)
        self.bc_from_base.setCurrentIndex(0)
        self.bc_to_base.setCurrentIndex(0)
        self.bo_from_base.setCurrentIndex(0)
        self.bo_to_base.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_4.setText(_translate("MainWindow", "To Base:"))
        self.label.setText(_translate("MainWindow", "Number:"))
        self.label_2.setText(_translate("MainWindow", "From Base:"))
        self.convert_button.setText(_translate("MainWindow", "Convert"))
        self.bc_result.setPlaceholderText(_translate("MainWindow", "Result..."))
        self.bc_number.setPlaceholderText(_translate("MainWindow", "Input number here..."))
        self.bc_from_base.setCurrentText(_translate("MainWindow", "Enter base number"))
        self.bc_from_base.setItemText(0, _translate("MainWindow", "Enter base number"))
        self.bc_from_base.setItemText(1, _translate("MainWindow", "2"))
        self.bc_from_base.setItemText(2, _translate("MainWindow", "3"))
        self.bc_from_base.setItemText(3, _translate("MainWindow", "4"))
        self.bc_from_base.setItemText(4, _translate("MainWindow", "5"))
        self.bc_from_base.setItemText(5, _translate("MainWindow", "6"))
        self.bc_from_base.setItemText(6, _translate("MainWindow", "7"))
        self.bc_from_base.setItemText(7, _translate("MainWindow", "8"))
        self.bc_from_base.setItemText(8, _translate("MainWindow", "9"))
        self.bc_from_base.setItemText(9, _translate("MainWindow", "10"))
        self.bc_from_base.setItemText(10, _translate("MainWindow", "11"))
        self.bc_from_base.setItemText(11, _translate("MainWindow", "12"))
        self.bc_from_base.setItemText(12, _translate("MainWindow", "13"))
        self.bc_from_base.setItemText(13, _translate("MainWindow", "14"))
        self.bc_from_base.setItemText(14, _translate("MainWindow", "15"))
        self.bc_from_base.setItemText(15, _translate("MainWindow", "16"))
        self.bc_from_base.setItemText(16, _translate("MainWindow", "17"))
        self.bc_from_base.setItemText(17, _translate("MainWindow", "18"))
        self.bc_from_base.setItemText(18, _translate("MainWindow", "19"))
        self.bc_from_base.setItemText(19, _translate("MainWindow", "20"))
        self.bc_from_base.setItemText(20, _translate("MainWindow", "21"))
        self.bc_from_base.setItemText(21, _translate("MainWindow", "22"))
        self.bc_from_base.setItemText(22, _translate("MainWindow", "23"))
        self.bc_from_base.setItemText(23, _translate("MainWindow", "24"))
        self.bc_from_base.setItemText(24, _translate("MainWindow", "25"))
        self.bc_from_base.setItemText(25, _translate("MainWindow", "26"))
        self.bc_from_base.setItemText(26, _translate("MainWindow", "27"))
        self.bc_from_base.setItemText(27, _translate("MainWindow", "28"))
        self.bc_from_base.setItemText(28, _translate("MainWindow", "29"))
        self.bc_from_base.setItemText(29, _translate("MainWindow", "30"))
        self.bc_from_base.setItemText(30, _translate("MainWindow", "31"))
        self.bc_from_base.setItemText(31, _translate("MainWindow", "33"))
        self.bc_from_base.setItemText(32, _translate("MainWindow", "34"))
        self.bc_from_base.setItemText(33, _translate("MainWindow", "35"))
        self.bc_from_base.setItemText(34, _translate("MainWindow", "36"))
        self.bc_to_base.setCurrentText(_translate("MainWindow", "Enter base number"))
        self.bc_to_base.setItemText(0, _translate("MainWindow", "Enter base number"))
        self.bc_to_base.setItemText(1, _translate("MainWindow", "2"))
        self.bc_to_base.setItemText(2, _translate("MainWindow", "3"))
        self.bc_to_base.setItemText(3, _translate("MainWindow", "4"))
        self.bc_to_base.setItemText(4, _translate("MainWindow", "5"))
        self.bc_to_base.setItemText(5, _translate("MainWindow", "6"))
        self.bc_to_base.setItemText(6, _translate("MainWindow", "7"))
        self.bc_to_base.setItemText(7, _translate("MainWindow", "8"))
        self.bc_to_base.setItemText(8, _translate("MainWindow", "9"))
        self.bc_to_base.setItemText(9, _translate("MainWindow", "10"))
        self.bc_to_base.setItemText(10, _translate("MainWindow", "11"))
        self.bc_to_base.setItemText(11, _translate("MainWindow", "12"))
        self.bc_to_base.setItemText(12, _translate("MainWindow", "13"))
        self.bc_to_base.setItemText(13, _translate("MainWindow", "14"))
        self.bc_to_base.setItemText(14, _translate("MainWindow", "15"))
        self.bc_to_base.setItemText(15, _translate("MainWindow", "16"))
        self.bc_to_base.setItemText(16, _translate("MainWindow", "17"))
        self.bc_to_base.setItemText(17, _translate("MainWindow", "18"))
        self.bc_to_base.setItemText(18, _translate("MainWindow", "19"))
        self.bc_to_base.setItemText(19, _translate("MainWindow", "20"))
        self.bc_to_base.setItemText(20, _translate("MainWindow", "21"))
        self.bc_to_base.setItemText(21, _translate("MainWindow", "22"))
        self.bc_to_base.setItemText(22, _translate("MainWindow", "23"))
        self.bc_to_base.setItemText(23, _translate("MainWindow", "24"))
        self.bc_to_base.setItemText(24, _translate("MainWindow", "25"))
        self.bc_to_base.setItemText(25, _translate("MainWindow", "26"))
        self.bc_to_base.setItemText(26, _translate("MainWindow", "27"))
        self.bc_to_base.setItemText(27, _translate("MainWindow", "28"))
        self.bc_to_base.setItemText(28, _translate("MainWindow", "29"))
        self.bc_to_base.setItemText(29, _translate("MainWindow", "30"))
        self.bc_to_base.setItemText(30, _translate("MainWindow", "31"))
        self.bc_to_base.setItemText(31, _translate("MainWindow", "33"))
        self.bc_to_base.setItemText(32, _translate("MainWindow", "34"))
        self.bc_to_base.setItemText(33, _translate("MainWindow", "35"))
        self.bc_to_base.setItemText(34, _translate("MainWindow", "36"))
        self.swap_button.setText(_translate("MainWindow", "Swap"))
        self.reset_button.setText(_translate("MainWindow", "Reset"))
        self.bc_clear.setText(_translate("MainWindow", "Clear"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Base Conversion"))
        self.bo_add.setText(_translate("MainWindow", "+"))
        self.bo_minus.setText(_translate("MainWindow", "-"))
        self.bo_mult.setText(_translate("MainWindow", "×"))
        self.bo_divide.setText(_translate("MainWindow", "÷"))
        self.bo_result.setPlaceholderText(_translate("MainWindow", "Result..."))
        self.bo_number.setPlaceholderText(_translate("MainWindow", "Input number here..."))
        self.label_3.setText(_translate("MainWindow", "Number:"))
        self.label_6.setText(_translate("MainWindow", "Base:"))
        self.bo_from_base.setCurrentText(_translate("MainWindow", "Enter base number"))
        self.bo_from_base.setItemText(0, _translate("MainWindow", "Enter base number"))
        self.bo_from_base.setItemText(1, _translate("MainWindow", "2 "))
        self.bo_from_base.setItemText(2, _translate("MainWindow", "3"))
        self.bo_from_base.setItemText(3, _translate("MainWindow", "4"))
        self.bo_from_base.setItemText(4, _translate("MainWindow", "5"))
        self.bo_from_base.setItemText(5, _translate("MainWindow", "6"))
        self.bo_from_base.setItemText(6, _translate("MainWindow", "7"))
        self.bo_from_base.setItemText(7, _translate("MainWindow", "8 "))
        self.bo_from_base.setItemText(8, _translate("MainWindow", "9"))
        self.bo_from_base.setItemText(9, _translate("MainWindow", "10"))
        self.bo_from_base.setItemText(10, _translate("MainWindow", "11"))
        self.bo_from_base.setItemText(11, _translate("MainWindow", "12"))
        self.bo_from_base.setItemText(12, _translate("MainWindow", "13"))
        self.bo_from_base.setItemText(13, _translate("MainWindow", "14"))
        self.bo_from_base.setItemText(14, _translate("MainWindow", "15"))
        self.bo_from_base.setItemText(15, _translate("MainWindow", "16 "))
        self.bo_from_base.setItemText(16, _translate("MainWindow", "17"))
        self.bo_from_base.setItemText(17, _translate("MainWindow", "18"))
        self.bo_from_base.setItemText(18, _translate("MainWindow", "19"))
        self.bo_from_base.setItemText(19, _translate("MainWindow", "20"))
        self.bo_from_base.setItemText(20, _translate("MainWindow", "21"))
        self.bo_from_base.setItemText(21, _translate("MainWindow", "22"))
        self.bo_from_base.setItemText(22, _translate("MainWindow", "23"))
        self.bo_from_base.setItemText(23, _translate("MainWindow", "24"))
        self.bo_from_base.setItemText(24, _translate("MainWindow", "25"))
        self.bo_from_base.setItemText(25, _translate("MainWindow", "26"))
        self.bo_from_base.setItemText(26, _translate("MainWindow", "27"))
        self.bo_from_base.setItemText(27, _translate("MainWindow", "28"))
        self.bo_from_base.setItemText(28, _translate("MainWindow", "29"))
        self.bo_from_base.setItemText(29, _translate("MainWindow", "30"))
        self.bo_from_base.setItemText(30, _translate("MainWindow", "31"))
        self.bo_from_base.setItemText(31, _translate("MainWindow", "33"))
        self.bo_from_base.setItemText(32, _translate("MainWindow", "34"))
        self.bo_from_base.setItemText(33, _translate("MainWindow", "35"))
        self.bo_from_base.setItemText(34, _translate("MainWindow", "36"))
        self.label_8.setText(_translate("MainWindow", "Base:"))
        self.bo_to_base.setCurrentText(_translate("MainWindow", "Enter base number"))
        self.bo_to_base.setItemText(0, _translate("MainWindow", "Enter base number"))
        self.bo_to_base.setItemText(1, _translate("MainWindow", "2 "))
        self.bo_to_base.setItemText(2, _translate("MainWindow", "3"))
        self.bo_to_base.setItemText(3, _translate("MainWindow", "4"))
        self.bo_to_base.setItemText(4, _translate("MainWindow", "5"))
        self.bo_to_base.setItemText(5, _translate("MainWindow", "6"))
        self.bo_to_base.setItemText(6, _translate("MainWindow", "7"))
        self.bo_to_base.setItemText(7, _translate("MainWindow", "8 "))
        self.bo_to_base.setItemText(8, _translate("MainWindow", "9"))
        self.bo_to_base.setItemText(9, _translate("MainWindow", "10"))
        self.bo_to_base.setItemText(10, _translate("MainWindow", "11"))
        self.bo_to_base.setItemText(11, _translate("MainWindow", "12"))
        self.bo_to_base.setItemText(12, _translate("MainWindow", "13"))
        self.bo_to_base.setItemText(13, _translate("MainWindow", "14"))
        self.bo_to_base.setItemText(14, _translate("MainWindow", "15"))
        self.bo_to_base.setItemText(15, _translate("MainWindow", "16 "))
        self.bo_to_base.setItemText(16, _translate("MainWindow", "17"))
        self.bo_to_base.setItemText(17, _translate("MainWindow", "18"))
        self.bo_to_base.setItemText(18, _translate("MainWindow", "19"))
        self.bo_to_base.setItemText(19, _translate("MainWindow", "20"))
        self.bo_to_base.setItemText(20, _translate("MainWindow", "21"))
        self.bo_to_base.setItemText(21, _translate("MainWindow", "22"))
        self.bo_to_base.setItemText(22, _translate("MainWindow", "23"))
        self.bo_to_base.setItemText(23, _translate("MainWindow", "24"))
        self.bo_to_base.setItemText(24, _translate("MainWindow", "25"))
        self.bo_to_base.setItemText(25, _translate("MainWindow", "26"))
        self.bo_to_base.setItemText(26, _translate("MainWindow", "27"))
        self.bo_to_base.setItemText(27, _translate("MainWindow", "28"))
        self.bo_to_base.setItemText(28, _translate("MainWindow", "29"))
        self.bo_to_base.setItemText(29, _translate("MainWindow", "30"))
        self.bo_to_base.setItemText(30, _translate("MainWindow", "31"))
        self.bo_to_base.setItemText(31, _translate("MainWindow", "33"))
        self.bo_to_base.setItemText(32, _translate("MainWindow", "34"))
        self.bo_to_base.setItemText(33, _translate("MainWindow", "35"))
        self.bo_to_base.setItemText(34, _translate("MainWindow", "36"))
        self.label_9.setText(_translate("MainWindow", "Result:"))
        self.bo_clear.setText(_translate("MainWindow", "Clear"))
        self.bo_equal.setText(_translate("MainWindow", "="))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Base Operations"))
        self.label_5.setText(_translate("MainWindow", "Statement:"))
        self.tt_statement.setPlaceholderText(_translate("MainWindow", "Input statement(s) here..."))
        self.tt_result.setPlaceholderText(_translate("MainWindow", "Result..."))
        self.tt_clear.setText(_translate("MainWindow", "Clear"))
        self.label_10.setText(_translate("MainWindow", "Result:"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("MainWindow", "Truth Tables"))
        self.label_7.setText(_translate("MainWindow", "Cross Product"))
        self.label_11.setText(_translate("MainWindow", "1st vector"))
        self.label_12.setText(_translate("MainWindow", "2nd vector"))
        self.label_13.setText(_translate("MainWindow", "x"))
        self.label_14.setText(_translate("MainWindow", "y"))
        self.label_15.setText(_translate("MainWindow", "z"))
        self.label_16.setText(_translate("MainWindow", "x"))
        self.label_17.setText(_translate("MainWindow", "y"))
        self.label_18.setText(_translate("MainWindow", "z"))
        self.label_19.setText(_translate("MainWindow", "n"))
        self.label_20.setText(_translate("MainWindow", "1st vector"))
        self.label_21.setText(_translate("MainWindow", "2nd vector"))
        self.label_22.setText(_translate("MainWindow", "n"))
        self.label_23.setText(_translate("MainWindow", "Dot Product"))
        self.add1.setText(_translate("MainWindow", "add"))
        self.add2.setText(_translate("MainWindow", "add"))
        self.label_24.setText(_translate("MainWindow", "Output:"))
        self.label_25.setText(_translate("MainWindow", "Output:"))
        self.calculate1.setText(_translate("MainWindow", "Calculate"))
        self.calculate2.setText(_translate("MainWindow", "Calculate"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), _translate("MainWindow", "Vectors"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
